name = "world-cities-bitrix24"
main = "src/install.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TENANT_CONFIG"
id = "e77e6fca25f74becbf65cdd57a9ebff2"
